### ISSUE TITLE
Error when launching twitchy.py

### ISSUE THREAD

**Issue by Sythee** [Andygmb/twitchy_the_bot#10]
F:\Desktop\V\HoN reddit\twitchy_the_bot-master>python twitchy.py
Logging in
C:\Python27\lib\site-packages\praw\decorators.py:87: DeprecationWarning: Password-based authentication will stop working
 on 2015/08/03 and as a result will be removed in PRAW4.
For more information please see: https://www.reddit.com/comments/2ujhkr/
Pass `disable_warning=True` to `login` to disable this warning.
  warn(msg, DeprecationWarning)
Checking inbox for new messages
Requesting stream info
Updating sidebar
Traceback (most recent call last):
  File "twitchy.py", line 227, in <module>
    livestreams.config.update_sidebar()
  File "twitchy.py", line 125, in update_sidebar
    start = desc.index(self.config["stream_marker_start"])
ValueError: substring not found

**Comment by Andygmb** [comment]
Make sure you have the two markers in your sidebar.

The markers by default are available here:

https://github.com/Andygmb/twitchy_the_bot/blob/master/default_wiki_config.json#L8-L9

Once you've run setup.py you can then also edit those markers in the respective wiki page. (/wiki/twitchbot_config)

So in your sidebar somewhere you'll need to include:

         [](#startmarker)  [](#endmarker)

With the whitespace inbetween them being where the twitch streams are placed by the bot.

--------

I'll also make an edit to the code to give a more informative message than the default python substring not found.
