### ISSUE TITLE
Unicode stream titles break end marker

### ISSUE THREAD

**Issue by diceroll123** [Andygmb/twitchy_the_bot#26]
Unicode characters take up 2 characters in a len() so if there are any in a stream title, this pushes the index of `end` (see `update_sidebar` function) to be further.

2 unicode characters makes the index 4 characters off, making the sidebar have `[](#endmarker)ker)ker)` (and so on) if it persists

**Comment by Andygmb** [comment]
Aha, didn't know len() used the amount of bytes as an indicator for length, and as unicode characters can be multiple bytes long. 

Will submit hotfix for this now.

**Comment by Andygmb** [comment]
I can't seem to replicate it with streams using unicode characters and as i'm currently at work I can't start up a test stream to test specific characters. Could you link any streams that have characters that are breaking the bot? 

Thanks

**Comment by diceroll123** [comment]
http://www.twitch.tv/yeezuswalks

The title that's broken it was `Yeezus ♠ ALWB Game vs APE ♠ Sponsored by EGO Gaming!`

**Comment by Andygmb** [comment]
Thank you. I've been able to recreate the bug with that string and will work on a fix.

**Comment by Andygmb** [comment]
@diceroll123 This should be fixed now, there are still some unicode issues I can foresee (users messaging non-ascii characters to the bot's inbox), but it should no longer have an issue with the stream titles. 

Will close this issue for now and move to a more generic issue:

https://github.com/Andygmb/twitchy_the_bot/issues/28

Please let me know if the issue hasn't been fixed or you encounter any other issues :)
