### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by revaNplays** [Andygmb/twitchy_the_bot#3]
Script worked fine till yesterday. I havent made any change to the server hosting it nor the inner configuration files but some of the mods might have played with the wiki config.

Logging in
Traceback (most recent call last):
  File "/home/ubuntu/twitchy_the_bot/twitchy.py", line 211, in <module>
    config = configuration()
  File "/home/ubuntu/twitchy_the_bot/twitchy.py", line 18, in __init__
    self.config = self.get_config()
  File "/home/ubuntu/twitchy_the_bot/twitchy.py", line 26, in get_config
    return HTMLParser.HTMLParser().unescape(json.loads(config))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Andygmb** [comment]
Yep, sounds like the wiki config was changed and that broke the bot, as it doesn't gracefully handle errors. I'll add some exception catching to sort it out, but if your wiki config is broken it still won't work. 

If you need a hand spotting what's broken, link me to your wiki config page (make sure it's public, or add /u/andygmb as an approved editor)

**Comment by Andygmb** [comment]
Assuming [this](https://www.reddit.com/r/TheRealmOfMianite/wiki/twitchbot_config) is your subreddit, you need to wrap Minecraft with quotes

    "allowed_games": [Minecraft]

Should be

    "allowed_games": ["Minecraft"]

**Comment by Andygmb** [comment]
Will now give more details as to whats gone wrong with

https://github.com/Andygmb/twitchy_the_bot/commit/50f780acb663fa725385222687a46b75b6d4d648
