### ISSUE TITLE
Twitchy not interacting with Twitch API due to required client-ID being missing

### ISSUE THREAD

**Issue by D0cR3d** [Andygmb/twitchy_the_bot#33]
Twitch is enforcing that a Client-ID be sent with every requests. This will prevent anyones instance of the bot from working because no client ID is being sent. Just need to add a headers with a client-id value to the api request.

**Comment by Andygmb** [comment]
Thanks for the issue - i'll get onto fixing this now.

**Comment by ev88** [comment]
Any progress?

**Comment by Andygmb** [comment]
Sorry, busy with work and traveling for the next 4 days - PRs welcome in the meantime and I can check via mobile. The fix is fairly simple, but I would like the README to be clear that people now a twitch.tv account to use the bot.

**Comment by Andygmb** [comment]
@D0cR3d @ev88 There is now a fix on master, my apologies for the long amount of time it took.
