### ISSUE TITLE
anyway to pull name from the page?

### ISSUE THREAD

**Issue by steinj13** [Andygmb/twitchy_the_bot#5]
Not really an issue, but a mod was bugging me about this and wouldn't let up. For each streamer, on their twitch page, the name as the correct capitalization (ex OMGitsfirefoxx, IIJERiiCHOII, etc), and I was wondering if there is any way to grab the name from there instead? ~ steinj (can get on anytime on snoonet #TheRealmOfMianite or pm /u/13steinj

**Comment by Andygmb** [comment]
See: 

https://github.com/Andygmb/twitchy_the_bot/commit/bcb521ea9f99793dad76df1e7369d8ec99385829

Use {display_name} in your wiki page string format to use the "pretty" name that's displayed on twitch.tv pages.
